### ISSUE TITLE
Shared files are recognized as folders

### ISSUE THREAD

**Issue by Tioxbew** [prrvchr/mDriveOOo#12]
Hi,

The new functionnality doesn't  seem to work for me, shared files (for example .docx) are recognized as folders. When I try to open it, it open a folder which is empty

**Comment by prrvchr** [comment]
In fact I did not test with shared files but only with shared folders...

I have to make sure that it is possible to differentiate one from the other easily...

**Comment by prrvchr** [comment]
Ok wasn't much to add, it should work with shared files too.

I did not change the version number but if you redownload you will have the last one.

Thank you for these tests, it saves me time...

**Comment by prrvchr** [comment]
I just fixed some last issues when saving shared files...

You have to re-download the extension with the commit: **Save shared files as it should**
