### ISSUE TITLE
No access to shared files

### ISSUE THREAD

**Issue by Tioxbew** [prrvchr/mDriveOOo#9]
There is a way to access and modify shared files ?

**Comment by Fa5g** [comment]
Same issue for me, I can't access OneDrive at all using Ubuntu 22.04.3 LTS an LibreOffice 7.5.5.2

**Comment by Tioxbew** [comment]
Ok, so it's not the same issue, because I access to my owned files but not when another people share me a file ..

**Comment by prrvchr** [comment]
Hi,
I confirm that the management of shared files is not implemented.
I see if it is possible.

**Comment by Fa5g** [comment]
> Hi, I confirm that the management of shared files is not implemented. I see if it is possible.

Ok, but is it possible open, close files from OpenDrive inside LibreOffice? I have followed the install tutorial, installed the three extensions on ubuntu: OAuth2OOo.oxt, jdbcDriverOOo.oxt, mDriveOOo.oxt and I couldn't get it to work.

**Comment by Tioxbew** [comment]
@prrvchr Thx, it would be useful for collaborative work to implemented that.

**Comment by prrvchr** [comment]
@Fa5g

It would have been better if you opened a new [issue](https://github.com/prrvchr/mDriveOOo/issues/new/choose).
Your problem is not the same as Tioxbew.

Can you launch LibreOffice in a terminal with:

- open a new terminal.
- type: soffice
- type: enter

and give me all errors appearing in this terminal when connecting.

**Comment by prrvchr** [comment]
Well, the new [mDriveOOo version 1.0.1](https://prrvchr.github.io/mDriveOOo/) manages shared files.

Shared folders must be created in the [OneDrive interface](https://onedrive.live.com)  and will be visible under the shared folder.

This shared folder can be renamed before any connection in:
**Tools -> Options -> Internet -> mDriveOOo -> Handle shared documents in folder:**

It may be that everything does not work perfectly on these new shared files, please create a new [issue](https://github.com/prrvchr/mDriveOOo/issues/new/choose) in the event of a malfunction.
